### ISSUE TITLE
Missing python version

### ISSUE THREAD

**Issue by milnus** [lrslab/Hammerhead#1]
I noticed tying to install HammerHead using `pip install Hammerhead-View` with python v. 3.11.5 resulted in the following error:
`ERROR: Ignored the following versions that require a different python version: 0.1.2 Requires-Python >=3.7, <=3.11; 0.1.3 Requires-Python >=3.7, <=3.11; 0.1.4 Requires-Python <=3.11,>=3.7; 0.2.0 Requires-Python <=3.11,>=3.7
ERROR: Could not find a version that satisfies the requirement Hammerhead-View (from versions: none)`

Downgrading to python v. 3.9.18 resulted in successful installation.
Can you make it clearer what python versions are expected for HammerHead?

**Comment by lxd98** [comment]
Hi milnus,

Thank you for your suggestion regarding Python compatibility. Hammerhead V0.2.0 now supports Python versions 3.7 through 3.11, as specified in the `setup.py` file. We also plan to expand support to additional versions in future updates and further clarify this in the README.
